### PR TITLE
eliminate dependency to axle

### PR DESCRIPTION
**Pull request by gavinking**
I've spent months wondering WTH this Axle thing was for, being too scared to ask anyone for fear of revealing to the world my stunning ignorance of everything related to Vert.x, assuming it *must* be doing *something* useful, even though clicking through the source code didn't seem to reveal anything much. Today I finally mustered up the courage to ask @FroMage and he told me it's just converting callbacks to `CompletionStage`s. So I copied the *two functions* we're actually using from this library and got rid of it.

It seems to me that this is manifestly the right thing to do, since:

- we're only using two pretty trivial functions of this lib
- it imposes additional wrapper classes on us
- it makes it much harder to change Vert.x driver versions

If nobody violently objects I'm going to merge this PR.

### CODE REVIEW

**Comment by DavideD** [comment]
Looks good. Feel free to merge it but I would squash the two commits into one.

**Comment by DavideD** [comment]
Thanks a lot

**Comment by gavinking** [comment]
> Feel free to merge it but I would squash the two commits into one.

Why is "Squash and merge" "not enabled for this repository"?

**Comment by gavinking** [comment]
> Why is "Squash and merge" "not enabled for this repository"?

Oh because we don't like merge commits?

**Comment by DavideD** [comment]
We like when everything is rebased to the latest change.

**Comment by gavinking** [comment]
Merged manually.

**Pull request closed without merging**
